# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - talent-place

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setear version de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      # comprimir y subir archivos para deploy
      - name: Crear el zip para deploy
        run: zip -r release.zip node_modules dist package.json package-lock.json

      - name: Subir el zip para el deploy job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Descargar el zip desde el build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Descomprimpir zip para el deploy
        run: unzip release.zip

      - name: Eliminar el zip despues de descomprimir
        run: rm release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B75D3C0D46F441149434466D7B93B5A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9F20698F7355405EBBD7E191033B63A1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_95EB2C48CDCB424487F6CC3BE7A6A7CC }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'talent-place'
          slot-name: 'Production'
          package: .
          # clean: true
          